# Generated by Django 4.2.7 on 2024-02-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamaapp', '0002_swipercontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MamamiaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField()),
                ('link_text', models.CharField(max_length=255)),
                ('link_url', models.URLField()),
                ('image', models.ImageField(upload_to='mamamia_images/')),
            ],
        ),
    ]
