# Generated by Django 4.2.7 on 2024-02-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamaapp', '0005_mamamiaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='mamamiaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='mamamia_images/')),
            ],
        ),
    ]
