# Generated by Django 4.2.7 on 2024-02-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamaapp', '0008_location_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mamamia_images/')),
            ],
        ),
    ]
