# Generated by Django 4.2.7 on 2024-02-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamaapp', '0009_associateimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
