# Generated by Django 4.2.7 on 2024-02-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamaapp', '0010_hiringinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringinfo',
            name='image_url',
        ),
        migrations.AddField(
            model_name='hiringinfo',
            name='image',
            field=models.ImageField(default='1', upload_to='mamamia_images/'),
        ),
    ]
