# Generated by Django 4.2.7 on 2024-02-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamaapp', '0017_mamamiaservices_sperm_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MamamiaServices_surrogacyr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('button_text', models.CharField(max_length=255)),
                ('button_url', models.URLField()),
                ('image', models.ImageField(upload_to='mamamia_images/')),
            ],
        ),
    ]
