# Generated by Django 4.2.5 on 2024-03-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamaapp', '0018_mamamiaservices_surrogacyr'),
    ]

    operations = [
        migrations.CreateModel(
            name='surrogacy_opening_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('image', models.ImageField(upload_to='mamamia_images/')),
            ],
        ),
    ]
