# Generated by Django 4.2.5 on 2024-03-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamaapp', '0020_surrogaterequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurrogateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
            ],
        ),
    ]
