# Generated by Django 4.2.5 on 2024-03-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamaapp', '0021_surrogatesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='surrogatesection',
            name='other_content',
            field=models.TextField(default='1'),
        ),
    ]
