# Generated by Django 4.2.5 on 2024-03-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamaapp', '0025_eligiblity_guildnes_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eligiblity_guildnes_section',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='eligiblity_guildnes_section',
            name='paragraph1',
            field=models.TextField(default='1'),
        ),
        migrations.AddField(
            model_name='eligiblity_guildnes_section',
            name='paragraph2',
            field=models.TextField(default='1'),
        ),
    ]
