# Generated by Django 4.2.5 on 2024-03-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamaapp', '0036_egg_eligibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='egg_steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
            ],
        ),
    ]
