# Generated by Django 4.2.5 on 2024-03-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamaapp', '0038_egg_donors_helpful'),
    ]

    operations = [
        migrations.CreateModel(
            name='egg_donor_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mamamia_images/')),
            ],
        ),
    ]
