# Generated by Django 4.2.5 on 2024-03-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamaapp', '0039_egg_donor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mamamia_images/')),
                ('heading', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
                ('button_text', models.CharField(blank=True, default='Default Button Text', max_length=255)),
                ('button_url', models.URLField(blank=True, default='https://example.com')),
            ],
        ),
        migrations.CreateModel(
            name='Aboutus_associates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mamamia_images/')),
                ('heading', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
                ('button_text', models.CharField(blank=True, default='Default Button Text', max_length=255)),
                ('button_url', models.URLField(blank=True, default='https://example.com')),
            ],
        ),
        migrations.CreateModel(
            name='Aboutus_people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mamamia_images/')),
                ('heading', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
                ('button_text', models.CharField(blank=True, default='Default Button Text', max_length=255)),
                ('button_url', models.URLField(blank=True, default='https://example.com')),
            ],
        ),
        migrations.CreateModel(
            name='why',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mamamia_images/')),
                ('heading', models.CharField(max_length=100)),
                ('heading1', models.CharField(max_length=100)),
                ('heading2', models.CharField(max_length=100)),
                ('heading3', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField()),
                ('paragraph3', models.TextField()),
                ('button_text', models.CharField(blank=True, default='Default Button Text', max_length=255)),
                ('button_url', models.URLField(blank=True, default='https://example.com')),
            ],
        ),
    ]
