# Generated by Django 4.2.5 on 2024-03-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamaapp', '0041_remove_faqs_answer_remove_faqs_question_faqs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='name',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
